// Code generated by "stringer -type=table"; DO NOT EDIT

package main

import "fmt"

const _table_name = "nationregionpartsupplierpartsuppcustomerorderslineitemnumTables"

var _table_index = [...]uint8{0, 6, 12, 16, 24, 32, 40, 46, 54, 63}

func (i table) String() string {
	if i < 0 || i >= table(len(_table_index)-1) {
		return fmt.Sprintf("table(%d)", i)
	}
	return _table_name[_table_index[i]:_table_index[i+1]]
}
